f = open('task1.txt', 'r')
f = f.readlines()
f = list(map(lambda x: str(x)[:-1], f))
f = [int(x) for x in f]
res = []

for x in f:
    for y in f:
        for z in f:
            if (x + y + z) == 2020:
                res.append(x * y * z)
res = list(set(res))  
print("В файл task1_output.txt пошли числа:", *res)


with open('task1_output.txt', 'w') as file:
    for x in res:
        file.write(str(x))
        file.write('\n')
file.close()




#далее след. программа



class d_exception(Exception):  # тут я делаю робкую попытку сделать свой эксепшн
    def __init__(self, text):
        self.txt = text


while True:
    try:
        key = input("Введите строку формата NdM, где N - количество кубиков, а M - количество сторон каждого из них: ")
        if 'd' not in key:
            raise d_exception("char 'd' is not in keyword")
        N = int(key[0])
        M = int(key[2:])
        cubes = [[x + 1 for x in range(M)] for _ in range(N)]
        break
    except Exception as e:
        print("Неправильный ввод, введите строку снова. Ошибка:", e)


s = [0]
for i in range(len(cubes)):
    cmb = [a + b for a in s for b in cubes[i]]
    s = [x for x in cmb]


for x in sorted((set(s))):
    print(x, '=', round(s.count(x)/len(s) * 100, 2), "%")
